package com.manuelblanco.capstonestage2.db;

import android.database.sqlite.SQLiteDatabase;

/**
 * Created by manuel on 31/07/16.
 */
public class CountriesISO {

    public static void loadCountriesISO(SQLiteDatabase db){

        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ad','Andorra');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ae','United Arab Emirates');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('af','Afghanistan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ag','Antigua and Barbuda');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ai','Anguilla');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('al','Albania');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('am','Armenia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('an','Netherlands Antilles');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ao','Angola');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('aq','Antarctica');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ar','Argentina');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('arpa','Old style Arpanet');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('as','American Samoa');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('at','Austria');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('au','Australia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('aw','Aruba');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('az','Azerbaidjan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ba','Bosnia-Herzegovina');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bb','Barbados');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bd','Bangladesh');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('be','Belgium');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bf','Burkina Faso');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bg','Bulgaria');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bh','Bahrain');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bi','Burundi');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bj','Benin');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bm','Bermuda');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bn','Brunei Darussalam');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bo','Bolivia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('br','Brazil');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bs','Bahamas');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bt','Bhutan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bv','Bouvet Island');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bw','Botswana');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('by','Belarus');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('bz','Belize');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ca','Canada');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cc','Cocos (Keeling) Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cf','Central African Republic');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cg','Congo');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ch','Switzerland');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ci','Ivory Coast');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ck','Cook Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cl','Chile');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cm','Cameroon');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cn','China');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('co','Colombia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('com','Commercial');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cr','Costa Rica');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cs','Former Czechoslovakia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cu','Cuba');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cv','Cape Verde');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cx','Christmas Island');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cy','Cyprus');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('cz','Czech Republic');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('de','Germany');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('dj','Djibouti');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('dk','Denmark');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('dm','Dominica');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('dom','Dominican Republic');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('dz','Algeria');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ec','Ecuador');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('edu','USA Educational');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ee','Estonia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('eg','Egypt');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('eh','Western Sahara');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('er','Eritrea');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('es','Spain');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('et','Ethiopia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('fi','Finland');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('fj','Fiji');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('fk','Falkland Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('fm','Micronesia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('fo','Faroe Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('fr','France');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('fx','France (European Territory)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ga','Gabon');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gb','Great Britain');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gd','Grenada');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ge','Georgia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gf','French Guyana');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gh','Ghana');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gi','Gibraltar');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gl','Greenland');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gm','Gambia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gn','Guinea');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gov','USA Government');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gp','Guadeloupe (French)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gq','Equatorial Guinea');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gr','Greece');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gs','S. Georgia & S. Sandwich Isls.');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gt','Guatemala');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gu','Guam (USA)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gw','Guinea Bissau');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('gy','Guyana');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('hk','Hong Kong');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('hm','Heard and McDonald Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('hn','Honduras');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('hr','Croatia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ht','Haiti');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('hu','Hungary');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('id','Indonesia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ie','Ireland');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('il','Israel');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('in','India');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('int','International');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('io','British Indian Ocean Territory');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('iq','Iraq');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ir','Iran');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('is','Iceland');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('it','Italy');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('jm','Jamaica');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('jo','Jordan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('jp','Japan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ke','Kenya');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('kg','Kyrgyzstan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('kh','Cambodia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ki','Kiribati');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('km','Comoros');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('kn','Saint Kitts & Nevis Anguilla');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('kp','North Korea');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('kr','South Korea');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('kw','Kuwait');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ky','Cayman Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('kz','Kazakhstan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('la','Laos');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('lb','Lebanon');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('lc','Saint Lucia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('li','Liechtenstein');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('lk','Sri Lanka');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('lr','Liberia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ls','Lesotho');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('lt','Lithuania');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('lu','Luxembourg');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('lv','Latvia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ly','Libya');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ma','Morocco');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mc','Monaco');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('md','Moldavia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mg','Madagascar');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mh','Marshall Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mil','USA Military');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mk','Macedonia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ml','Mali');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mm','Myanmar');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mn','Mongolia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mo','Macau');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mp','Northern Mariana Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mq','Martinique (French)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mr','Mauritania');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ms','Montserrat');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mt','Malta');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mu','Mauritius');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mv','Maldives');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mw','Malawi');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mx','Mexico');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('my','Malaysia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('mz','Mozambique');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('na','Namibia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('nato','NATO (this was purged in 1996 - see hq.nato.int)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('nc','New Caledonia (French)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ne','Niger');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('net','Network');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('nf','Norfolk Island');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ng','Nigeria');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ni','Nicaragua');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('nl','Netherlands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('no','Norway');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('np','Nepal');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('nr','Nauru');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('nt','Neutral Zone');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('nu','Niue');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('nz','New Zealand');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('om','Oman');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('org','Non-Profit Making Organisations (sic)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pa','Panama');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pe','Peru');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pf','Polynesia (French)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pg','Papua New Guinea');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ph','Philippines');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pk','Pakistan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pl','Poland');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pm','Saint Pierre and Miquelon');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pn','Pitcairn Island');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pr','Puerto Rico');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pt','Portugal');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('pw','Palau');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('py','Paraguay');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('qa','Qatar');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('re','Reunion (French)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ro','Romania');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ru','Russian Federation');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('rw','Rwanda');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sa','Saudi Arabia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sb','Solomon Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sc','Seychelles');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sd','Sudan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('se','Sweden');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sg','Singapore');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sh','Saint Helena');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('si','Slovenia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sj','Svalbard and Jan Mayen Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sk','Slovak Republic');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sl','Sierra Leone');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sm','San Marino');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sn','Senegal');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('so','Somalia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sr','Suriname');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('st','Saint Tome (Sao Tome) and Principe');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('su','Former USSR');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sv','El Salvador');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sy','Syria');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('sz','Swaziland');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tc','Turks and Caicos Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('td','Chad');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tf','French Southern Territories');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tg','Togo');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('th','Thailand');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tj','Tadjikistan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tk','Tokelau');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tm','Turkmenistan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tn','Tunisia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('to','Tonga');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tp','East Timor');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tr','Turkey');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tt','Trinidad and Tobago');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tv','Tuvalu');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tw','Taiwan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('tz','Tanzania');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ua','Ukraine');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ug','Uganda');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('uk','United Kingdom');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('um','USA Minor Outlying Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('us','United States');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('uy','Uruguay');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('uz','Uzbekistan');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('va','Vatican City State');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('vc','Saint Vincent & Grenadines');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ve','Venezuela');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('vg','Virgin Islands (British)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('vi','Virgin Islands (USA)');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('vn','Vietnam');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('vu','Vanuatu');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('wf','Wallis and Futuna Islands');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ws','Samoa');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('ye','Yemen');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('yt','Mayotte');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('yu','Yugoslavia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('za','South Africa');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('zm','Zambia');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('zr','Zaire');");
        db.execSQL("INSERT INTO countries (iso,name) VALUES ('zw','Zimbabwe');");
    }
}
